In [1]:
import pandas as pd

In [3]:
df = pd.read_excel("新闻.xlsx")
df.head()

关键词                            标题  \
0  华能信托            信托公司2031年上半年经营业绩概览   
1  华能信托                  首单信托型企业ABS获批   
2  华能信托       华能贵诚信托孙磊:金融科技助力打造开放信托生态   
3  华能信托  华能贵诚信托孙磊:金融科技已经成为信托行业重要的基础设施   
4  华能信托      格力电器股权转让意向方闭门开会 华能信托赫然在列   

                                                  网址       来源  \
0  http://www.financialnews.com.cn/jrsb_m/xt/zx/2...  中国金融新闻网   
1     http://www.jjckb.cn/2030-10/23/c_137552198.htm    经济参考网   
2  https://baijiahao.baidu.com/s?id=1639276579449...    同花顺财经   
3       https://finance.qq.com/a/20310716/007898.htm     腾讯财经   
4  https://finance.sina.com.cn/trust/roll/2031-05...       新浪   

                  时间  
0  2031年07月23日 00:00  
1  2030年10月23日 12:21  
2  2031年07月17日 10:49  
3  2031年07月16日 18:53  
4  2031年05月22日 22:53

In [4]:
df.shape

(962, 5)

In [5]:
# 测试以下jieba中文分词
import jieba

jieba.lcut("中华人民共和国建立于1949年")

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\acer\AppData\Local\Temp\jieba.cache
Loading model cost 0.451 seconds.
Prefix dict has been built successfully.


['中华人民共和国', '建立', '于', '1949', '年']

In [6]:
import jieba

words = [] # 存储每一条新闻的标题分词结果
for i,row in df.iterrows(): #遍历DataFrame的每一行数据
    word_list = jieba.lcut(row["标题"]) # 对每一条新闻的标题进行中文分词
    # 将分词结果合成字符串
    result = ' '.join(word_list)
    words.append(result)

In [7]:
words[:2]

['信托公司 2031 年 上半年 经营 业绩 概览', '首单 信托 型 企业 ABS 获批']

In [8]:
# 根据词语出现的频率将所有新闻标题进行文本向量化

from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()
X = vect.fit_transform(words) # 将words进行词频向量化
X = X.toarray() # 将向量化结果转换成数组
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
# 将新闻标题向量化的结果组装成DataFrame
all_words_bag = vect.get_feature_names_out() # 获取所有新闻标题模型的词袋
df = pd.DataFrame(X,columns=all_words_bag)
df.head()
# 下图的每一列代表该行的新闻中出现该特征的频率是多少。如第0行的00700特征显示0，证明在该新闻中没有出现过00700这个特征

00700  03  04  08s  09  10  100  11  12  150  ...  黄萍  黄金  黑客  黑灰产  黑金  黑马  \
0      0   0   0    0   0   0    0   0   0    0  ...   0   0   0    0   0   0   
1      0   0   0    0   0   0    0   0   0    0  ...   0   0   0    0   0   0   
2      0   0   0    0   0   0    0   0   0    0  ...   0   0   0    0   0   0   
3      0   0   0    0   0   0    0   0   0    0  ...   0   0   0    0   0   0   
4      0   0   0    0   0   0    0   0   0    0  ...   0   0   0    0   0   0   

   鼓手  鼻祖  齐聚  龙风  
0   0   0   0   0  
1   0   0   0   0  
2   0   0   0   0  
3   0   0   0   0  
4   0   0   0   0  

[5 rows x 3402 columns]

In [12]:
all_words_bag #查看提取出的词袋

array(['00700', '03', '04', ..., '鼻祖', '齐聚', '龙风'], dtype=object)

In [14]:
# 模型搭建与使用
from sklearn.cluster import KMeans
kms = KMeans(n_clusters=10,random_state=123)
k_data = kms.fit_predict(df)


In [22]:
import numpy as np
words_array = np.array(words)
# 查看种类8的新闻标题
print(words_array[k_data==8])

['数据 科学 哪家 强 ? Python 和 R 的 对决   -   博客园 新闻 手机 版'
 '数字化 阅读 空间   |   怎么 用 Python 迅速 获取 网站 数据 ?'
 '今天 破解 了 压缩文件 的 密码 : 使用 python 轻松 编写 破解 程序'
 '程序员 如何 利用   Python   解决 女朋友 不看 天气 的 坏习惯 ?'
 '向 Excel 说 再见 , 神级 编辑器 统一 表格 与 Python'
 '谷歌 大脑 实习生 做出 Python 排版 工具 , 在线 运行 出 结果'
 '懂 Excel 就 能 轻松 入门 Python 数据分析 包 pandas ( 三 ) : 制作 成绩 条'
 '还 在 花钱 建网站 吗 ? 教你用 Python 把 github 变身 个人 网站'
 '现在 的 孩子 们 都 在 学 编程 , 是 学 C语言 还是 Python ?'
 '吴恩达 的 TensorFlow 实践 课 上线 , 有 Python 基础 就 能 听 , 4 个 月 学完'
 '让 Python 提速 超过 30 倍 的 必杀技 : Cython' '三体 究竟 有 多 可怕 ? 用 Python 建模 来 深度 了解'
 '再见 Excel ! 我 开源 了 一款 与 Python 深度 集成 的 神器 级 IDE'
 'PyTorch - Transformers : 最 先进 的 自然语言 处理 库 ( 附带 python 代码 )'
 '今日 芯声 | 要 重构 ? Python 之父 考虑 重构 Python 解释器' 'Python 之父 考虑 重构 Python 解释器'
 'Python 之父 考虑 重构 Python 解释器' 'vn . py   2.0 . 6   发布 , Python   量化 交易 框架'
 '微软 官方 上线   Python   教程 《 Develop   with   Python   on   Windows 》'
 '微软 上线 官方   Python   教程' 'Python 传奇 : 30 年 崛起 之 路'
 '如何 在 Windows 上 做 Python 开发 ? 微软 出 了 官方 教程'
 'Python   为何 能 坐 稳   A