In [1]:
import torch

In [2]:
a = torch.Tensor([1,2,3])
b = torch.Tensor([2,3,4])
torch.dot(a,b) # 點乘，即a1*b1+a2*b2+a3*b3

tensor(20.)

In [3]:
a.dot(b)

tensor(20.)

In [7]:
a = torch.Tensor([[1,2,3],[2,3,4],[3,4,5]])
b = torch.Tensor([1,2,3])

In [6]:
a

tensor([1., 2., 3.])

In [9]:
torch.mv(a,b) # 矩陣與向量相乘 matrix vector times vector

tensor([14., 20., 26.])

In [10]:
a = torch.Tensor([[1,2,3],[2,3,4],[3,4,5]])
b = torch.Tensor([[2,3,4],[3,4,5],[4,5,6]])

In [11]:
torch.mm(a,b)

tensor([[20., 26., 32.],
        [29., 38., 47.],
        [38., 50., 62.]])

In [13]:
a = torch.rand(2,2)
a

tensor([[0.2491, 0.8847],
        [0.7889, 0.1256]])

In [14]:
torch.t(a)

tensor([[0.2491, 0.7889],
        [0.8847, 0.1256]])