In [8]:
import torch

In [9]:
a = torch.rand(2,2)
b = torch.rand(2,2)

In [10]:
a,b

(tensor([[0.0186, 0.8019],
         [0.5316, 0.9614]]),
 tensor([[0.6256, 0.8262],
         [0.8905, 0.4199]]))

In [11]:
# 連接操作
torch.cat((a,b),0) # 在0維度（垂直方向）上連接

tensor([[0.0186, 0.8019],
        [0.5316, 0.9614],
        [0.6256, 0.8262],
        [0.8905, 0.4199]])

In [12]:
torch.cat((a,b),1) # 在1維度（水平方向）上連接

tensor([[0.0186, 0.8019, 0.6256, 0.8262],
        [0.5316, 0.9614, 0.8905, 0.4199]])

In [13]:
# 切片操作
c = torch.rand(2,4)
c

tensor([[0.3472, 0.1040, 0.7494, 0.4515],
        [0.1138, 0.9238, 0.9908, 0.9272]])

In [14]:
torch.chunk(c,2,1) # 将張量c，在1維度切分成2份

(tensor([[0.3472, 0.1040],
         [0.1138, 0.9238]]),
 tensor([[0.7494, 0.4515],
         [0.9908, 0.9272]]))

- 變形操作

In [15]:
X = torch.rand(2,3,4)
X

tensor([[[0.6912, 0.6100, 0.9194, 0.7671],
         [0.1925, 0.0939, 0.7748, 0.8048],
         [0.1051, 0.4404, 0.6966, 0.1607]],

        [[0.2503, 0.7455, 0.8392, 0.5142],
         [0.6039, 0.8791, 0.7005, 0.5667],
         [0.7693, 0.4345, 0.9410, 0.8383]]])

In [16]:
X.size()

torch.Size([2, 3, 4])

In [18]:
y = X.view(2,12)
y.size()

torch.Size([2, 12])

In [19]:
y

tensor([[0.6912, 0.6100, 0.9194, 0.7671, 0.1925, 0.0939, 0.7748, 0.8048, 0.1051,
         0.4404, 0.6966, 0.1607],
        [0.2503, 0.7455, 0.8392, 0.5142, 0.6039, 0.8791, 0.7005, 0.5667, 0.7693,
         0.4345, 0.9410, 0.8383]])